version: "3.1"

services:
  # mongo_cms:
  #   image: mongo
  #   restart: always
  #   container_name: mongo_cms
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: root
  #   ports:
  #     - 27017:27017
  #   volumes:
  #     - /study/mongo_datas:/data/db
  redis_cms:
    image: redis
    restart: always
    container_name: redis_cms
    ports:
      - 6379:6379
    volumes:
      - /study/redis_data:/data
    command: ["redis-server", "--requirepass", "123456"]
  mysql_cms:
    image: "mysql:5.7"
    container_name: mysql_cms
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "1111qqqq"
      MYSQL_USER: "jkadmin"
      MYSQL_PASS: "1111qqqq"
    volumes:
      - /study/mysql/data:/var/lib/mysql # 挂载数据目录
      - /study/mysql/config:/etc/mysql/conf.d # 挂载配置文件目录
