version: "3.1"

services:
  mongo_cms:
    image: mongo
    restart: always
    container_name: mongo_cms
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    volumes:
      - /study/mongo_datas:/data/db
  redis_cms:
    image: redis
    restart: always
    container_name: redis_cms
    ports:
      - 6379:6379
    volumes:
      - /study/redis_data:/data
    command: ["redis-server", "--requirepass", "123456"]
  mysql_cms:
    image: "mysql:5.7"
    container_name: mysql_cms
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "1111qqqq"
      MYSQL_USER: "jkadmin"
      MYSQL_PASS: "1111qqqq"

  DOClever:
    image: lw96/doclever:latest
    restart: always
    container_name: "DOClever"
    ports:
      - 10000:10000
    volumes:
      - /study/hostdir/file:/root/DOClever/data/file
      - /study/hostdir/img:/root/DOClever/data/img
      - /study/hostdir/tmp:/root/DOClever/data/tmp
    environment:
      - DB_HOST=mongodb://doclever:123456@localhost:27017/DOClever
      - PORT=10000
